### ISSUE TITLE
export 'default' (imported as 'plugin1') was not found in 'plugin1'

### ISSUE THREAD

**Issue by BjornMelgaard** [nuxt/nuxt.js#1179]
if plugin doesnt import anything, the warning is thrown

```
 WARNING  Compiled with 2 warnings                                                                                            5:39:47 PM

 warning  in ./.nuxt/index.js

107:25-32 "export 'default' (imported as 'plugin1') was not found in 'plugin1'

 warning  in ./.nuxt/index.js

113:19-26 "export 'default' (imported as 'plugin1') was not found in 'plugin1'
```
and page is loading with infinite reloading

P.S. workaround `export default (_) => { }`

**Comment by BjornMelgaard** [comment]
```
[HMR] bundle has 2 warnings
client.js:161 ./.nuxt/index.js
126:25-32 "export 'default' (imported as 'plugin3') was not found in 'plugin3'
./.nuxt/index.js
132:19-26 "export 'default' (imported as 'plugin3') was not found in 'plugin3'
process-update.js:27 [HMR] Checking for updates on the server...
process-update.js:122 [HMR] Update check failed: Error: Manifest request to /_nuxt/62fa7e6c4dcbc909dbc4.hot-update.json timed out.
    at XMLHttpRequest.request.onreadystatechange (http://localhost:3000/_nuxt/manifest.62fa7e6c4dcbc909dbc4.js:68:22)
handleError @ process-update.js:122
cb @ process-update.js:33
manifest.62fa7e6c4dcbc909dbc4.js:68 Uncaught (in promise) Error: Manifest request to /_nuxt/62fa7e6c4dcbc909dbc4.hot-update.json timed out.
    at XMLHttpRequest.request.onreadystatechange (manifest.62fa7e6c4dcbc909dbc4.js:68)
```

**Comment by pi0** [comment]
@BjornMelgaard Really thanks for helping for finding problems with RCs :) This will be resolved in next release. Currently as you mentioned simple workaround is a noop export default at the end of plugins:
```js
export default () => { }
```

**Comment by BjornMelgaard** [comment]
@pi0 Don't mention it :)

**Comment by mgesmundo** [comment]
@pi0 Thank you for your hard work!
We are really excited for the upcoming 1.0 release!!
All the best

**Comment by pi0** [comment]
This problem should now be resolved. Just upgrade to `rc3+`!

**Comment by mgesmundo** [comment]
Thanks @pi0 🙂

**Comment by joshua1** [comment]
on rc4 still facing the same issue. plugin i have in place is vue-notification, added to the nuxt.config plugins and vendor sections still getting same error

**Comment by tonyrewin** [comment]
moving plugins code to somewhere else works for me, but rc11 still having this issue
