### ISSUE TITLE
Config local favicon failure

### ISSUE THREAD

**Issue by kunsam** [nuxt/nuxt.js#1204]
version: "nuxt": "^1.0.0-rc3"

**nuxt.config.js:**

``link: [{ rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }]``
`favicon.ico` was put in /static folder, I also try put it in root dir of project.

The favicon doesn't display but it's right when use http res like `https://modao.cc/favicon.ico`

**Comment by kunsam** [comment]
Reference link: 
[https://github.com/nuxt/nuxt.js/blob/1f6c3a9a7bd67907d5bb85cce010f3bf09f3639b/examples/typescript/nuxt.config.js](https://github.com/nuxt/nuxt.js/blob/1f6c3a9a7bd67907d5bb85cce010f3bf09f3639b/examples/typescript/nuxt.config.js)

I use the example config

**Comment by alexchopin** [comment]
Fixed in the last release

**Comment by kristraeger** [comment]
Hello! i installed nuxt.js today (1.4) and used both the starter template as well as build a project from scratch. This issue still appears for me. Even in the starter template it does not show the favicon for /favicon.ico - please help :)

**Comment by ms-webdev** [comment]
Hi @kristraeger, I had the same issue.

In my case, the problem was with NGINX where the access to the favicon was intercepted:

```
# location = /favicon.ico { access_log off; log_not_found off; }
# location = /robots.txt  { access_log off; log_not_found off; }
```


Maybe it helps you

**Comment by kelleysy** [comment]
the same is happening for me

**Comment by wuweijia** [comment]
the same is happening for me

**Comment by devpaps** [comment]
Same here

**Comment by smiller171** [comment]
Yeah, this is not in fact fixed. I can't get a favicon working and I have no idea where nuxt is sending the wrong instruction to the browser

**Comment by kelleysy** [comment]
i added a query string to the favicon and it worked for me. don't know if it will help but something like..`href: '/favicon.ico?v=2'`
