### ISSUE TITLE
Prerendering doesn't respect `baseURL`

### ISSUE THREAD

**Issue by gnehs** [nuxt/nuxt.js#13810]
### Environment

------------------------------
- Operating System: `Darwin`
- Node Version:     `v16.14.2`
- Nuxt Version:     `3.0.0-rc.1`
- Package Manager:  `npm@8.5.0`
- Builder:          `vite`
- User Config:      `-`
- Runtime Modules:  `-`
- Build Modules:    `-`
------------------------------

### Reproduction

- `npx nuxi init nuxt-app`
- `cd nuxt-app`
- `npm install`
- `NUXT_APP_BASE_URL=/foo npm run generate`

### Describe the bug

When NUXT_APP_BASE_URL is specified, the deployed file does not have index.html
#### not specify NUXT_APP_BASE_URL

```
> npm run generate
> tree ./.output/public 
├── _nuxt
│   ├── entry-79c674ce.mjs
│   ├── entry.93eb12fa.css
│   └── manifest.json
└── index.html

1 directory, 4 files
```
#### specify NUXT_APP_BASE_URL
```
> NUXT_APP_BASE_URL=/foo npm run generate
> tree ./.output/public
.
└── _nuxt
    ├── entry-79c674ce.mjs
    ├── entry.93eb12fa.css
    └── manifest.json

1 directory, 3 files
```
missing index.html :(

### Logs

```shell
> generate
> nuxt generate

Nuxt CLI v3.0.0-rc.1                                                    16:21:28
ℹ Vite client warmed up in 1652ms                                       16:21:34
ℹ Client built in 1674ms                                                16:21:34
ℹ Building server...                                                    16:21:34
✔ Server built in 563ms                                                 16:21:34
✔ Generated public .output/public                                 nitro 16:21:34
ℹ Initializing prerenderer                                        nitro 16:21:34
ℹ Prerendering 1 initial routes with crawler                      nitro 16:21:37
  ├─ / (47ms) (Error: [404] Not Found)                            nitro 16:21:37
✔ You can now deploy .output/public to any static hosting!              16:21:37
```

**Comment by oneart-dev** [comment]
Using prerender for some routes with SWR enabled lead to all assets not respecting baseUrl despite html and payload being rendered just fine in the latest nuxt version

**Comment by danielroe** [comment]
@oneart-dev Would you create a new issue with a reproduction? 🙏

**Comment by oneart-dev** [comment]
@danielroe fixed by specifying baseUrl literally everywhere it accepts it. In nuxt config in nitro config then in bash script.
I think nuxt should respect app config and use it as default if not specified different.

**Comment by danielroe** [comment]
@oneart-dev Indeed it should. If you open an issue with a reproduction it will be possible to investigate.

**Comment by richtera** [comment]
This still doesn't seem to work. I have tried like 1000 different ways now and I just can't get baseURL to work. I tried checking things with hooks and so on, but no matter what something is rewriting the app config. When I look into my output page it just ends up says `{ app: { baseURL: "/" .... } }` :( Has this not been resolved yet or did it re-appear as a new bug? I am using nuxt ```console
Working directory: /Users/andy/Development/example-miniapps/apps/nuxt                                                                                                              nuxi 5:59:27 PM
Nuxt project info: (copied to clipboard)                                                                                                                                           nuxi 5:59:27 PM

------------------------------
- Operating System: Darwin
- Node Version:     v22.12.0
- Nuxt Version:     3.15.1
- CLI Version:      3.20.0
- Nitro Version:    2.10.4
- Package Manager:  yarn@4.6.0
- Builder:          -
- User Config:      compatibilityDate, devtools, css, modules, postcss, vue, ssr, graphql-client
- Runtime Modules:  nuxt-graphql-client@0.2.43
- Build Modules:    -
------------------------------
```
Maybe it's something about the other plugins, but so far I have not gotten it to work.

**Comment by danielroe** [comment]
@richtera If you open an issue with a reproduction it will be possible to investigate.

**Comment by richtera** [comment]
I did find something which might be related. If I use the old NITRO_PRESET environment variable rather than the new ʼ—-nitro-presetʼ command line arg it seems to break the baseURL.

**Comment by richtera** [comment]
I think the path variable would be best to calculate using __dirname, because otherwise it's always very subjective which one is right :)

**Comment by richtera** [comment]
I will create this as a new issue now.
