### ISSUE TITLE
import router from '~router' stopped working

### ISSUE THREAD

**Issue by iamdubx** [nuxt/nuxt.js#1664]
Hello. I had a fix for scrolling to top behavior when page transition, but with latest Nuxt releases it stoped working. It was a plugin:

```
import router from '~router'

router.afterEach((to, from) => {
  setTimeout(() => {
    if (document) document.body.scrollTop = 0
  }, 515)
})
```
But now this `import router from '~router'` gives me an error. 

Any tips how to fix it? How to access router with latest API?

**Comment by homerjam** [comment]
Can you try `import router from '~/router'`

**Comment by iamdubx** [comment]
@homerjam nope

```
This dependency was not found:

* ~/router in ./plugins/scrolltotop.js

To install it, you can run: npm install --save ~/router
```

**Comment by christophwolff** [comment]
Try it like this: (actually code i use in an app.  ;-) )
```
export default ({ app }) => {
  app.router.afterEach((to, from) => {
    /*
      Scroll up Container. The router ScrollBehavoir wont work because we have an overflow: auto element where all the flex action happens.
     */
    setTimeout(() => {
      var elmnt = window.document.getElementsByClassName('content-container')[0]
      if (elmnt) elmnt.scrollTop = 0
    }, 500)
  })
}
```
You need to pass your `app`.
It is also possible to pass `{ router }` only and then `router.afterEach...`

**Comment by christophwolff** [comment]
Sorry there was an mistake. i corrected it!

**Comment by iamdubx** [comment]
@christophwolff I need this as a plugin? Where should I put this?

**Comment by iamdubx** [comment]
Not sure what this apply to `content-container`

**Comment by christophwolff** [comment]
sorry i thought a made it clear that this was my code... wait.

**Comment by iamdubx** [comment]
I guess it's applied to wrapper in `default.vue`?

**Comment by christophwolff** [comment]
```
export default ({ app }) => {
  app.router.afterEach((to, from) => {
    setTimeout(() => {
    	if (document) document.body.scrollTop = 0
  	}, 515)
  })
}
```
put it in a plugin. i.E. `scrollUp.js` 
And then in your `nuxt.config.js` :
```
plugins: [
    '~/plugins/scrollUp.js',
  ],
...
```  
You dont need

**Comment by iamdubx** [comment]
I tried it. Unfortunatly, it still jerking to top before page transition.

**Comment by christophwolff** [comment]
ahh okay. i thought your issue was the import of router. i think that is fixed isnt it?
Maybe it would be good to open a new issue then.

**Comment by iamdubx** [comment]
What fixed? I don't see any fixes. 
I still can't access router to change it behavior. Your code is not working.

**Comment by iamdubx** [comment]
With code above now I have this error

```
ReferenceError: document is not defined
    at Timeout._onTimeout (server-bundle.js:3894:7)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
npm ERR! code ELIFECYCLE

```

**Comment by christophwolff** [comment]
try `window.document.body.scrollTop = 0`

**Comment by christophwolff** [comment]
```
export default ({ app }) => {
  app.router.afterEach((to, from) => {
    setTimeout(() => {
      window.document.body.scrollTop = 0
    }, 515)
  })
}
```

**Comment by iamdubx** [comment]
Still error. 
If I add ssr: false then no error, but no desired effect.

**Comment by christophwolff** [comment]
ok i found it. you need to disable the default scroll behavoir in nuxt config
```
  router: {
    scrollBehavior: function (to, from, savedPosition) {
      if (savedPosition) return savedPosition
      return false
    }
  },
```

**Comment by iamdubx** [comment]
@christophwolff now this is so cool, man, I don't know how to thank you! It is working!

**Comment by christophwolff** [comment]
You are welcome. :)

**Comment by iamdubx** [comment]
For some weird reason this stopped working today!!!

**Comment by iamdubx** [comment]
I noticed that in Firefox it's still working. It doesn't work in my Chromiujm.

**Comment by christophwolff** [comment]
If it is rendering realy long pages it does not work for me. Please close this issue. and open a new one. The title isnt in no way related to the issue. maybe someone else knows help.

**Comment by iamdubx** [comment]
Why title is unrelated? I can't modify router setting. It's still related. It has nothing to do with `long pages`. It's still the same pages that was yesterday. Today it is not working.

**Comment by iamdubx** [comment]
This is stopped working basically

```js
export default ({ app }) => {
  app.router.afterEach((to, from) => {
    setTimeout(() => {
      window.document.body.scrollTop = 0
    }, 300)
  })
}

```

**Comment by christophwolff** [comment]
do you have a page transition animation?

**Comment by iamdubx** [comment]
Of course I have

**Comment by christophwolff** [comment]
how long is it?

**Comment by iamdubx** [comment]
It's unrelated. 300ms. I didn't change anything. Yesterday it was working.

**Comment by christophwolff** [comment]
so please, bare with me. iam asking questions here to find **your** issue. I dont know what happend since yesterday...

**Comment by christophwolff** [comment]
```export default ({ app }) => {
  app.router.afterEach((to, from) => {
    setTimeout(() => {
      window.document.body.scrollTop = 0
    }, 315)
  })
}```
Try 315ms

**Comment by iamdubx** [comment]
315 ms - no effect

**Comment by iamdubx** [comment]
Looks like it's just returns `savedPosition`. This router interception is not working at all.

**Comment by christophwolff** [comment]
try to return only false in nuxt conf

router: {
    scrollBehavior: function (to, from, savedPosition) {
      return false
    }
  },

**Comment by homerjam** [comment]
The true fix for this is going to come from vue-router not from nuxt. I've submitted a PR which gets us some way to transition support from scrollBehavior - but AFAIK it will always be a workaround.

What @christophwolff is getting at is there could be a delay rendering the page which means the scrolling isn't occurring at the time you need.

@iamdubx it would help if you could post more code, error messages and preferably an isolated reproduction of the issue.

**Comment by iamdubx** [comment]
scrolltotop.js plugin

```js
export default ({ app }) => {
  app.router.afterEach((to, from) => {
    setTimeout(() => {
      window.document.body.scrollTop = 0
    }, 300)
  })
}
```

nuxt.config.js

```js
router: {
    scrollBehavior: function (to, from, savedPosition) {
      if (savedPosition) return savedPosition
      return false
    }
  },
  plugins: [
    { src: 'plugins/scrolltotop.js', ssr: false }
  ]
```

page transition styling

```
.page-enter-active,
.page-leave-active
  transition: opacity 300ms
  will-change: opacity

.page-enter,
.page-leave-active
  opacity: 0
```

This is all related code.

**Comment by iamdubx** [comment]
@homerjam can you please give a link to that PR that I can know what is happening?

**Comment by christophwolff** [comment]
@homerjam its working fine for me. I think the issue is the savePosition. It will work even when i throttle my network without any animations.

@iamdubx try only to return a false in scrollBehavoir

**Comment by homerjam** [comment]
https://github.com/vuejs/vue-router/pull/1758

**Comment by iamdubx** [comment]
@christophwolff hm... Now this is weird. No changes

```js
scrollBehavior: function (to, from, savedPosition) {
      return false
    }
```

**Comment by christophwolff** [comment]
@iamdubx weird? what exactly?

**Comment by iamdubx** [comment]
Why it still save position if I am not returning it value?

**Comment by homerjam** [comment]
```
if (savedPosition) return savedPosition
```

Doesn't account for `savedPosition = 0` right?

Have you tried...
```
if (typeof savedPosition === 'object') return savedPosition
```

**Comment by iamdubx** [comment]
Just tried this, but see no changes. Scrollbar still stuck on one place.

**Comment by iamdubx** [comment]
@homerjam I see that PR is fresh. Finger crossed this will work. :smile:

**Comment by christophwolff** [comment]
For me its just working fine. With and wihtour animation. Page throttling and not. Even on chrome canary, safari and firefox. i have no clue

**Comment by iamdubx** [comment]
Hm, let me try on fresh project. Thanks for info.

**Comment by christophwolff** [comment]
scroll.js
```javascript
export default ({ app }) => {
  app.router.afterEach(function (to, from, next) {
    setTimeout(() =>{
      window.scrollTo(0, 0)
    },115)
  })
}
```
nuxt.conf.js
```javascript
  router: {
    scrollBehavior (to, from, savedPosition) {
      if (savedPosition) return savedPosition
      return false
    }
  }
```
_animation.scss
```sass
.page-enter-active, .page-leave-active {
  transition: opacity .1s;
}
.page-enter, .page-leave-to {
  opacity: 0;
}
```

**Comment by iamdubx** [comment]
@christophwolff here you go. Clean project. Scroll to top doesn't work at all! Can you confirm it? http://special-ladybug.surge.sh/scroll

**Comment by iamdubx** [comment]
@christophwolff I tried `window.scrollTo(0, 0)` instead of `window.document.body.scrollTop = 0` and it's magically begin to work again :smile: 

I have no idea what is happening right now. Yesterday `window.document.body.scrollTop = 0` was working. Today it's not but `window.scrollTo(0, 0)` is working. 

I guess, thanks again @christophwolff

**Comment by christophwolff** [comment]
your website isnt working in chrome canary. I think it was with `window.document.body.scrollTop = 0` right?

you are welcome.

**Comment by iamdubx** [comment]
Closing this, but still hopes this can be fix in `vue-router`

**Comment by marchuksergii** [comment]
Hey! I`m also tired to find fix for this issue. Thanks for snippet above.

Instead of _scroll.js_, we can define in _nuxt.config.js_:
`transition: {
    afterLeave () {
      window.scrollTo(0, 0)
    }
  },`
