### ISSUE TITLE
pages mounted more than once when using customized layout other than default.

### ISSUE THREAD

**Issue by dreambo8563** [nuxt/nuxt.js#1710]
1. using starter template
2. create a new layout
3. using your layout in one page, console log sth in mounted.
you will see the log twice
remove the layout prop(using default), only mounted once

**Comment by Vanessa219** [comment]
I have the same question, pls help me

**Comment by alexchopin** [comment]
Fixed in the last release

**Comment by Vanessa219** [comment]
fixed in which version?

**Comment by artfree** [comment]
June 22, 2018.  It's still happening.  Page mounted twice when using a custom layout on that page.
