### ISSUE TITLE
router.push() is not working in latest nuxt release

### ISSUE THREAD

**Issue by SaranyaPalanivel** [nuxt/nuxt.js#2737]
router.push() is not reloading the page contents in the latest nuxt release while changing the URL query

i.e
For pagination, when clicking the 2nd page, URL is changed by `this.$router.push({query: {'page': 2}})`.
Usually router.push() will call from created hook. But now its only changing the url query and its not refreshing data.

**Comment by marchuksergii** [comment]
Same issue, someone have any suggestions? Or its a new way to update an url query without data fetch?

**Comment by Zip753** [comment]
I've also experienced some weird bugs with updating the query string using `vue-router`, but some of them disappeared when I specified the name of the page/route explicitly, so say your page lives under `pages/home.vue`, then instead of this
```javascript
this.$router.push({ query: { page: 2 } })
```
I would do this
```javascript
this.$router.push({ name: 'home', query: { page: 2 } })
```
and some bugs would just go away :sweat_smile:

**Comment by xxxxxMiss** [comment]
maybe you can watch the `$route` and trigger the load data method:smile:

**Comment by marchuksergii** [comment]
It appears only in production. In dev mode works fine as expected.

**Comment by geodeveloper** [comment]
Same here, `this.$router.push` not working.

**Comment by AngelWayfarer** [comment]
For me, the router push is working, even in production, I have the problem only when pushing another query into the same route. The url changes, but the fetch method doesnt fire:(

**Comment by awronski** [comment]
@AngelWayfarer you need to add watch query:
https://github.com/nuxt/nuxt.js/issues/2519


```js
export default {
    watchQuery: ['yourQueryName'],
    [...]
}
```

**Comment by AngelWayfarer** [comment]
@awronski thank you for help!
I have another related issue:
I have next structure:
```
/pages/
   search.vue
   search/
      index.vue <-----FILE (here is the problem)
```
``` javascript
export default {
	scrollToTop: true, //<-------------------------- A
	watchQuery: [
		'query',
		'page',
		'order-type',
		'order',
		'price-from',
		'price-to',
		'per_page'],
	key: (to) => to.fullPath,
	name: 'SearchResultsList',
	components: {
		ProductCard
	},
	fetch ({app, store, route}) {
		return app.$axios.get(route.fullPath, {
			params: {
				with: ['meta', 'breadcrumbs', 'actions']
			}
		}).then(response => {
			store.commit('routeDataSaved', response.data)
		})
	},
	data () { // <----------------------- B
		let {routeData} = this.$store.state
		return {
			meta: routeData.meta,
			products: routeData.items
		}
	}
}
```

So, 'A' had started to work only after adding this https://github.com/nuxt/nuxt.js/issues/2738#issuecomment-362485495 to nuxt.config.js insead the "native" function that is "out of the box".

And 'B' doesn't fire on changing query in th route even after adding "watchQuery" key.
BUT, it have been started work after I renamed the FILE into _slug.vue instead of index.vue

**Comment by Zip753** [comment]
@awronski Thanks for pointing this out! I've tried using this new undocumented breaking feature (seriously, what kind of attitude to users is that? :confused:), but it doesn't quite work. After some debugging it turned out that `asyncData` gets called once again on params update, but new result from `asyncData` isn't persisted in `data` later.

**Comment by theomjones** [comment]
I also have a similar issue. 
`<nuxt-link>` is working fine, but navigation with `router.push()` is buggy. Most of the time the route just isn't updated, and I just get a blank page, the loading bar reaches completion but just stays there. Sometimes it does work though, it's inconsistent.

I've found the most consistent behaviour is using: `router.push('path/:id')` for example (`id` being your dynamic route value). It seems to act as consistently as navigation links in templates.

**Comment by husayt** [comment]
@Atinux @alexchopin 
this is quite serious. I have also experienced what @Zip753 saying:

> After some debugging it turned out that asyncData gets called once again on params update, but new result from asyncData isn't persisted in data later.

This creates massive inconsistency and also means we can't really use asyncdata on pages with params update. To me this is a bug. 

asyncData behavior should be consistent on first and latter calls.

**Comment by signal-intrusion** [comment]
Is the vue `$router` not being injected into components like the `$store`?

We found a workaround. use `this.$store.$router`

**Comment by husayt** [comment]
@signal-intrusion it's a different issue here

**Comment by dohomi** [comment]
I see the same issue. I use asyncData and this is the call cycle:
```
State A
stateChange to State B
asyncData => destroyed => mounted
```
I think asyncData should be called after the destroyed hook. I also don't see any chance to add a `$route` watch and as a result the scrollToTop behaviour is broken

**Comment by Atinux** [comment]
Could someone create a small repo to reproduce this issue, otherwise it's pretty hard for me to know where to fix this behaviour :/

**Comment by dohomi** [comment]
@Atinux I don't have a repo to show at the moment (still in the process to separate my code). But online you can see the behaviour: 
https://dev.planet.training
The issue happens due to the custom route I implemented in nuxt.config.js:
```
extendRoutes (routes, resolve) {
      routes.push({
        name: 'article',
        path: '*',
        component: resolve(__dirname, 'src/pages/index.vue')
      })
    }
```
The index.vue consist of `asyncData`where an API call is made to the graphql server to fetch the content of the page. 
I hope I can publish sometimes soon the cms but currently its not ready, I still investigate other issues as well.

**Comment by Zip753** [comment]
@Atinux there you go: https://github.com/Zip753/nuxt-router-push-issue-repro
The description is in the README.

**Comment by Atinux** [comment]
This commit should fix it: https://github.com/nuxt/nuxt.js/commit/8903db1c27942088754b8a37568e8fc364ed8c66

Thanks for your reproduction @Zip753, it helped me a lot to fix quickly this particular issue.

I will release next version this week :)

**Comment by iampawan31** [comment]
Hi, just to confirm, this issue is still there in version 1.4.0 right?

**Comment by Atinux** [comment]
This issue is fixed in 1.4.0, if you found a regression, please provide a reproduction repo @iampawan31 :)

**Comment by iampawan31** [comment]
@Atinux This issues seems to be fixed in the 1.4.0. Would like to confirm if the following piece of code is required to make it work.

````
export default {
    watchQuery: ['yourQueryName'],
}
````

**Comment by imfaber** [comment]
It works with watchQuery but page transitions are gone. Is it meant to be so?

**Comment by dfeinberg5** [comment]
I'm still seeing an issue with this.$router.push() in Nuxt 1.4.0...

I need to update the query parameters in my route any time the underlying data changes, so I have a watcher on the different items. For example, when selectedLocations changes, I want to push a route to reflect the latest query.

The watcher is being triggered properly, but this.$router.push() isn't firing.

**Comment by NemoAlex** [comment]
Still need the `watchQuery` to get it work in Nuxt 1.4.0.
Hope it could be documented if it's not a bug.

**Comment by NemoAlex** [comment]
Update:

I added this to my code
```
watchQuery: ['page'],
```
After refresh the page, when I do `this.$router.push` to update the query first time, asyncData didn't called.
But it works since the second time query updated.

Nuxt.js 1.4.0

**Comment by NemoAlex** [comment]
Update:

This may caused by vue-router?
My code was:
```
      this.$router.push({
        path: `/news/${this.category}/`,
        query: { page }
      })
```
After I change to use router name, the issue has gone:
```
      this.$router.push({
        name: 'news-category',
        query: { page }
      })
```

**Comment by dfeinberg5** [comment]
I tried using `watchQuery` but it still wasn't working for me. Ultimately the only way I got it working was by moving my data out of my Vuex store and into `asyncData` in my component. Previously I had been using `fetch` and watching for changes to data in the store.

I don't know why that would affect `this.$router.push()` but it seems to.

**Comment by sharh** [comment]
`this.$router.push('to/path?query=query')`, this will cause the data(){} function excuted twice. In v1.4.0

**Comment by sudhir600** [comment]
Hi @Atinux I am also facing the same issue. even tryied as described by @awronski  but it didn't work.

Here is my work scenario - 
User come to login page.. click on login, uses verified.
Once user verification done.. i need to redirect to home page. so what i am doing is

```
doLogin(){
	this.checkLogin()
	common.setCookie('accessToken', 'XXXXX') // mixins/common.js
	this.$router.push('/')  // use need to redirect homepage
       // this.$router.push({ name: 'index' }) it also not work
}
```
So, is there any alternate option other than native JavaScript.


<img width="677" alt="router issue" src="https://user-images.githubusercontent.com/4952560/39424416-4186a96e-4c94-11e8-9b63-cb73a5242a1d.png">

**Comment by Atinux** [comment]
@sudhir600 this should works, it seems that you are checking `req.headers` in your middleware where `req` is not defined.

**Comment by sudhir600** [comment]
Hi @Atinux, above code is not written in middleware. I have created a  mixins (session.js) and imported into login component. 

Here is my code- 

_mixins/session.js_
```
import axios from 'axios'
import Vuex from 'vuex'
import store from '~/store'
import common from '~/lib/common.js'

export default {
	methods: {
		doLogin(){
			this.checkLogin()
			common.setCookie('accessToken', 'sudhir')
			this.$router.push({ name: 'index'}) // this one not working
			//location.replace('/')
		},
		checkLogin(){
			console.log('checkLogin Called123')
		}
	}
}
```
and in _login.vue_

```
<script>
import session from '~/mixins/session' 
export default {
	mixins: [session],
}
</script>
```

HTML -
`<button type="button" v-on:click="doLogin()" ... />`

there is no code in middleware related to this.

in above mixing if i use l`ocation.replace('/') `then its work fine but i want to via proper nuxt way.

**Comment by memic84** [comment]
I have the same issue, when trying to add a query to the same page, where the query already exists. Any workaround for now?

We are not using the auth.nuxtjs plugin, just a simple middleware implementation.

**Comment by sudhir600** [comment]
No, I am not using `auth.nuxtjs.org`. 
However, now i am using `location.replace('/')` `instead this.$router.push('/')` bcz i didn't found any solution yet.

**Comment by Atinux** [comment]
Can you share you Auth middleware please?

**Comment by bidos** [comment]
I have the same issue. i have problem with router.push only if i use an async middelware. In this case i have 'an error occure' in the middle of the page (in place of nuxt element).

**Comment by threeid** [comment]
@bidos Same here.
@sudhir600 location.replace('/') will change page as expected. But it will freeze page/component that use router.

**Comment by delrueba** [comment]
I ran into this issue when updating an array inside the query: the url does not update.
Altering a random $route.query property before replacing the entire query does the trick.

Let's say the query is as follows
```
{
  values[]: [
    value_1, value_2, value_3
  ]
}
```

```
// Results in NaN, doesn't matter since we replace the query anyway
this.$route.query.check++

this.$router.push({
  // Replace existing query
  query: { values[]: [ value_1 ] }
})
```
