### ISSUE TITLE
SASS: tilde package reference is broken on SSR

### ISSUE THREAD

**Issue by ChristianKlee** [nuxt/nuxt.js#4060]
### Version

[v2.1.0](https://github.com/nuxt.js/releases/tag/v2.1.0)

### Reproduction link

[https://github.com/ChristianKlee/nuxt-fonts-test](https://github.com/ChristianKlee/nuxt-fonts-test)

### Steps to reproduce

Install nuxt-fonts-test and switch between my master (Nuxt 2.1) and nuxt-142 (Nuxt 1.4.2) branch to see the error.

### What is expected ?

The font of a NPM Module (in this example node_modules/test/Charmonman.ttf) are included and after a nuxt generate in the dist folder

### What is actually happening?

Error Message "SyntaxError: Invalid or unexpected token" on nuxt and nuxt generate.

### Additional comments?

Since Nuxt 2.0 it isn't possible to use an NPM package as a style library with fonts. 
The reproduction link based on create-nuxt-app with the only addition to include a global sass file and a custom NPM module "test" with a font.
If I comment line 3 of screen.scss everything runs fine, without the included font-family.
On all version before Nuxt 2.0 it was possible to include such a NPM module. 
Based on the release notes, I can't identify this as a feature/different implementation but maybe I overlook something.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c7917">#c7917</a>)</em></sub></div>

**Comment by manniL** [comment]
This does work when using `~/test/...` (with a slash after the tilde).

Example CSB: https://codesandbox.io/s/zl7464jo53

**Comment by ChristianKlee** [comment]
No, this only "fixes" the error message but you could write what ever you want (e.g. ~/test/Test.tff) and there will be no error. The font file is not used at all from the node package.

**Comment by manniL** [comment]
@ChristianKlee Please check out the linked CSB.

![image](https://user-images.githubusercontent.com/640208/46543529-fed96d80-c8b8-11e8-8cf7-7393f9664b1b.png)

**Comment by manniL** [comment]
You are right! Will investigate.

**Comment by manniL** [comment]
@ChristianKlee Temporary workaround: `  src: url("../node_modules/test/Charmonman.ttf");`

**Comment by manniL** [comment]
Even better workaround that does not involve complete relative paths: `src: url("~~test/Charmonman.ttf");`

**Comment by manniL** [comment]
@ChristianKlee I tried to reproduce it with a "real" package like font-awesome and were not able to 🤔 

See https://codesandbox.io/s/zl7464jo53 again.

**Comment by manniL** [comment]
Not stale

**Comment by shuaqiu** [comment]
I also encountered this problem when I migrated the version from 1.4 to 2.x.  It seems that it can be temporarily solved by the above method.

**Comment by clarkdo** [comment]
@ChristianKlee Could you try to upgrade to 2.4.2 and test it again, I tried it based on your repo, it works fine with:


```js
// copy Charmonman.ttf to node_modules/test/ Then
yarn upgrade nuxt@^2.4.2
yarn dev
```

**Comment by manniL** [comment]
@clarkdo Can still reproduce it via https://codesandbox.io/s/zl7464jo53 :|

**Comment by clarkdo** [comment]
It seemed there is an error in rendering, I'll look into it
