### ISSUE TITLE
使用element-ui执行npm run build 时报错

### ISSUE THREAD

**Issue by imlida** [nuxt/nuxt.js#4143]
ERROR in ./node_modules/element-ui/lib/theme-chalk/index.css (./node_modules/css-loader??ref--3-oneOf-1-1!./node_modules/postcss-loader/src??ref--3-oneOf-1-2!./node_modules/element-ui/lib/theme-chalk/index.css)
Module build failed (from ./node_modules/postcss-loader/src/index.js):
TypeError: Cannot read property 'search' of undefined

无法完成编译，报错到底是哪里的问题？

**Comment by kruny1001** [comment]
+1

**Comment by WangHansen** [comment]
same issue

**Comment by WangHansen** [comment]
The workaround right now is to disable the postcss by the following config:
```javascript
// nuxt.config.js
    build: {
        postcss: false,
        extend ..
    }
```

**Comment by sunlei4076** [comment]
same issue!!!

**Comment by sunlei4076** [comment]
same issue

**Comment by minooo** [comment]
@WangHansen well, It works....

**Comment by uncleLian** [comment]
同样问题。。。

**Comment by aldarund** [comment]
it seems like issue with cssnano 
https://github.com/cssnano/cssnano/issues/644

**Comment by jhd4tmr** [comment]
+1

**Comment by aldarund** [comment]
@jhd4tmr it was already fixed in cssnano 4.1.7

**Comment by jhd4tmr** [comment]
@aldarund Actually it happened only in my main project. The others' projects are ok. But whatever versions of different packages i changed, the problem still exists in my main project. The main project used to be ^1.4.7 nuxt. I update nuxt, sass-loader ... element-ui and the all the other packages to the newest version, but the problem still exists. The main project is quite big, i solve the problem by adding the small components into the css config of  nuxt.config.js like button.css, display.css. After I removed index.css, everything works fine. holy shit.

**Comment by aldarund** [comment]
@jhd4tmr u need only updat cssnano to 4.1.7 to ger rid of error in this ticket
