### ISSUE TITLE
@babel/preset-env/data/built-ins.json has been removed from babel

### ISSUE THREAD

**Issue by dzeroone** [nuxt/nuxt.js#5286]
### Version

[v2.4.5](https://github.com/nuxt.js/releases/tag/v2.4.5)

### Reproduction link

[https://qx9nql3y49.sse.codesandbox.io/](https://qx9nql3y49.sse.codesandbox.io/)

### Steps to reproduce

Just follow latest nuxtjs installation procedure.

### What is expected ?

nuxtjs running

### What is actually happening?

client build failed

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c8869">#c8869</a>)</em></sub></div>

**Comment by chz** [comment]
Exactly same problem. Cant create 
`npx create-nuxt-app`

**Comment by creador** [comment]
I'm having the same problem here.

**Comment by AnthonyFromTheVault** [comment]
I'm having this problem as well, both on new projects using `npx create-nuxt-app`, but also on fresh installs of my existing nuxt app.

**Comment by vsergiu93** [comment]
It seems that a fix has been merge https://github.com/babel/babel/pull/9711

**Comment by scottyadean** [comment]
npm install --save-dev @babel/preset-env
fixed my latest project

**Comment by kristremblay** [comment]
Here I was thinking it was just me.  I chose a hell of a time to decide to try Nuxt heh.

@scottyadean this was my first instinct, but it didn't solve the problem.

**Comment by kristremblay** [comment]
@vsergiu93 after applying the fix, I'm still receiving `isPluginRequired is not a function`.  I managed to get a function by importing directly from `@babel/preset-env/lib/filter-items` but this yielded an error of `no property "ie"`.

A little lost.

**Comment by vsergiu93** [comment]
@kristremblay All I did was to make sure I have updated `@babel/preset-env` package to `7.4.1` then I ran `yarn upgrade`

**Comment by kristremblay** [comment]
@vsergiu93 Just deleted `node_modules`, updated `package.json`, and installed from scratch.  Works now, thanks :)

**Comment by pi0** [comment]
Thanks folks for reporting this issue and closing this as there seems a bad release from babel caused that and there is workaround for this issue.

**Comment by dasZGFz** [comment]
@pi0 It might be helpful to rollback https://github.com/nuxt/nuxt.js/commit/f5f1471bc5d205064e4c10e9c956ba6e88721975 until this gets addressed appropriately. I imagine that it will be resolved in the following days so requiring developers to add the workaround seems more detrimental than helpful.

**Comment by pi0** [comment]
@dasZGFz downgrading in `package.json` does not simply fixes this issue unless using `~7.3.4` constraint.

**Comment by dasZGFz** [comment]
@pi0 That commit also alters the yarn.lock file. As far as I'm aware, that's the breaking commit so I would assume reverting it would fix the issue.

It's entirely possible that I'm overlooking something but I don't think I am.

**Comment by pi0** [comment]
The `yarn.lock` is NOT published with npm packages but only used for nuxt development and CI tests. What babel version users get installed with fresh `create-nuxt-app` is the latest version of babel that this constraint allows which is `7.4.0`.

Please follow-up other answers by cleaning up your project's lock file and installing again.

**Comment by pi0** [comment]
The "With useBuiltIns option, required direct setting of corejs option" warning is going to be resolved by #5291. (Thanks to @clarkdo)

**Comment by dasZGFz** [comment]
@pi0 Ah I see. Thank you for clarifying. What I was looking for was locking the babel version, not the yarn.lock file itself. 

Glad to see a PR already emerge aiming to resolve this issue. Thanks for the hard work!

**Comment by manniL** [comment]
Resolved by #5291 :relaxed:

**Comment by clarkdo** [comment]
For the users who are using `yarn` and need a quick fix before next Nuxt release:

Add `resolutions` in `package.json`
```json
"resolutions": {
  "@babel/preset-env": "7.3.1"
}
```

**Comment by pi0** [comment]
Babel 7.4.0 support is resolved with [v2.5.1](https://github.com/nuxt/nuxt.js/releases/tag/v2.5.1). You can now safely remove the `resolutions` field.
