### ISSUE TITLE
latest version of nuxt-edge breaks webpack build (css-loader issue)

### ISSUE THREAD

**Issue by Cl3MM** [nuxt/nuxt.js#5996]
### Version

[v2.9.0](https://www.npmjs.com/package/nuxt-edge)

### Reproduction link

[https://github.com/Cl3MM/nuxt-css-loader-failure/tree/nuxt-edge-2.9.0-26026572.fc5502cd](https://github.com/Cl3MM/nuxt-css-loader-failure/tree/nuxt-edge-2.9.0-26026572.fc5502cd)

### Steps to reproduce

git clone https://github.com/Cl3MM/nuxt-css-loader-failure.git
cd nuxt-css-loader-failure
git checkout nuxt-edge-2.9.0-26026572.fc5502cd
yarn
yarn build

### What is expected ?

no error

### What is actually happening?

ERROR in ./pages/index.vue?vue&type=style&index=0&id=f6a825ce&lang=scss&scoped=true& (./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-1-1!./node_modules/@nuxt/webpack-edge/node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--9-oneOf-1-2!./node_modules/sass-loader/lib/loader.js??ref--9-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=style&index=0&id=f6a825ce&lang=scss&scoped=true&)
Module build failed (from ./node_modules/css-loader/dist/cjs.js):
ValidationError: CSS Loader Invalid Options

options should NOT have additional properties

    at validateOptions (/dev/nuxt-css-loader-failure/node_modules/schema-utils/src/validateOptions.js:32:11)
    at Object.loader (/dev/nuxt-css-loader-failure/node_modules/css-loader/dist/index.js:44:28)
 @ ./pages/index.vue?vue&type=style&index=0&id=f6a825ce&lang=scss&scoped=true& (./node_modules/vue-style-loader??ref--9-oneOf-1-0!./node_modules/css-loader/dist/cjs.js??ref--9-oneOf-1-1!./node_modules/@nuxt/webpack-edge/node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--9-oneOf-1-2!./node_modules/sass-loader/lib/loader.js??ref--9-oneOf-1-3!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=style&index=0&id=f6a825ce&lang=scss&scoped=true&) 4:14-425
 @ ./pages/index.vue?vue&type=style&index=0&id=f6a825ce&lang=scss&scoped=true&
 @ ./pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

### Additional comments?

Related to nuxt-edge@latest, but not available in dropdown list.
See issue https://github.com/nuxt/nuxt.js/issues/5995 closed by the nice CMTY bot.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9426">#c9426</a>)</em></sub></div>

**Comment by clarkdo** [comment]
@pi0 @manniL @Cl3MM I'll look into this.

**Comment by clarkdo** [comment]
@Cl3MM Could your try latest edge, issue should have been fixed.

```sh
yarn upgrade nuxt-edge@latest
```

**Comment by Cl3MM** [comment]
@clarkdo quick feedback: I've tried the latest version (`2.9.0-26033769.1a49902e`) and the issue still persists, though I did not push my tests very far.

I've done the following steps :

```
yarn remove nuxt-edge
yarn clean cache
yarn add nuxt-edge@latest
```

I also tried the latest `nuxt-edge` in a fresh docker container, and the issue still persists there as well.

I'll try to do some more tests tonight.

**Comment by clarkdo** [comment]
The issue seemed because of your local css-loader is still v2 which is already v3 in current nuxt-edge.

Could you remove node_modules folder and try install again ? If still no work, please paste the css-loder version here

```sh
yarn why css-loader
```

**Comment by clarkdo** [comment]
Another issue I found in your branch is that you've installed both `nuxt` and `nuxt-edge`, please remove `nuxt` when you wanna use `nuxt-edge`

**Comment by Cl3MM** [comment]
@clarkdo removing the reference to `nuxt@2.8.1` fixes the issue !

Thanks a lot ;)
