### ISSUE TITLE
`nuxt build` fails at generating pages in spa mode

### ISSUE THREAD

**Issue by alexkcollier** [nuxt/nuxt.js#6500]
### Version

[v2.10.0](https://github.com/nuxt.js/releases/tag/v2.10.0)

### Reproduction link

[https://gitlab.com/alexkcollier/nuxt-build-repro](https://gitlab.com/alexkcollier/nuxt-build-repro)

### Steps to reproduce

1. Create nuxt project
1. Set mode to `spa` in `nuxt.config.js`
1. `yarn build`

### What is expected ?

Build succeeds

### What is actually happening?

`FATAL  Cannot read property 'renderRoute' of undefined`

![error.png](https://cmty.s3.eu-west-1.amazonaws.com/71995937/eef70b80-e521-11e9-8d25-214efa15b4f1.png)

### Additional comments?

`yarn generate` works as expected, and so does building in universal mode.

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c9850">#c9850</a>)</em></sub></div>

**Comment by 1001v** [comment]
I have the same issue on 2.10. There're no problems with 2.9.1.

**Comment by AndrewBogdanovTSS** [comment]
It happens not only in SPA mode but also in Universal, with and without a `--modern` flag. Dev mode is working fine though

**Comment by Teranode** [comment]
Can also confirm this happening with 2.10.0
2.9 and below works fine.

**Comment by AlexSwtlsk** [comment]
Same here

**Comment by sbrieuc** [comment]
Same here

**Comment by AndrewBogdanovTSS** [comment]
Guys, please, do not pollute the topic with the same messages. It's already clear that a lot of us have this issue

**Comment by moritzsternemann** [comment]
Looks like the breaking change happened in the `@nuxt/generator@2.10.0` update. Works fine using `2.9.1`.

**Comment by liyasthomas** [comment]
Build fails in Docker. Same here while generating pages in 'spa' mode.

`TypeError: Cannot read property 'renderRoute' of undefined`

**Comment by josepjaume** [comment]
Same happens to me!

**Comment by AndrewBogdanovTSS** [comment]
@pi0 @manniL maybe you could provide some update on whether this issue is being addressed by the Nuxt team? Thank you

**Comment by jmartinezuk** [comment]
Same here. Went back to 2.9.1 until it's fixed.

**Comment by SamJakob** [comment]
I had this issue but I went back to 2.9.2 which also worked fine.

**Comment by catisnorm** [comment]
> Same happens to me on `2.10.0` but I tried reverting to `2.9.1` without success - maybe it's cause a transient dependency?

Did you removed node_modules and package-lock?
https://nuxtjs.org/guide/upgrading#npm

**Comment by madmod** [comment]
I ran into this after removing `package-lock.json` and `node_modules` while working on something unrelated. A fresh `npm i` with `package.json` set to `"2.9.2"` fixed the issue.

**Comment by vinayakkulkarni** [comment]
Related issues: #6514 & #6513

**Comment by riux** [comment]
I imagine that this error is solved in the next version

**Comment by AndrewBogdanovTSS** [comment]
@riux it better be since now 2.10.0 is not usable for many people

**Comment by edellaq** [comment]
I'm not very fond of these things, but while tweaking here and there think I was able to build my SPA using 'npm run generate' instead of 'npm run build' (that gave the error)...

**Comment by vinayakkulkarni** [comment]
Fixed via https://github.com/nuxt/nuxt.js/commit/136777de1d7924f052c803c6397530de80bdea50

**Comment by riux** [comment]
I still have the error after changing to nuxt 2.9.2 (remove node_modules and yarn.lock from src / and from function /). This only happens when deploying in firebase hosting. The error occurs when I update the "f5" page in a different index path (domain.com/video/id_video). I clarify that this error does not occur in (yarn dev, nor in yarn start) 
![image](https://user-images.githubusercontent.com/9002215/66523402-8271ff80-eab5-11e9-9086-2cf5bd69d673.png)

**Comment by laitingyou** [comment]
![image](https://user-images.githubusercontent.com/28053563/66547093-105ef080-eb71-11e9-97f8-72b53c85e68a.png)
Waiting for a new version to be released.

**Comment by vinayakkulkarni** [comment]
this has been already fixed in #6525 

#6529 is v2.10.1

**Comment by alexkcollier** [comment]
`nuxt@2.10.1` has been released, fixing the issue

**Comment by riux** [comment]
Well, I haven't updated to the new version yet. But I discovered that this error occurred for two reasons: 1) .Use the nuxt functions (asyncData, fetch) on a page with dynamic URL (search / _stringSearch.vue), then I had to change these functions to created () {. ..}.
2) I also found it necessary to attach the content of my page (search / _stringSearch.vue), with <client-only>
Page content </client-only>. My development environment is a universal application that uses the firebase and firebase hosting functions. As I mentioned, the error occurred at the time of the test in Firebase Hosting (Nuxt Build, Firebase Implement)
![image](https://user-images.githubusercontent.com/9002215/66688326-c72f9f00-ec4b-11e9-9dc9-d21e7b16b976.png)
![image](https://user-images.githubusercontent.com/9002215/66688359-e0d0e680-ec4b-11e9-8e3f-8366739e253f.png)
![image](https://user-images.githubusercontent.com/9002215/66688389-078f1d00-ec4c-11e9-966c-b78040180cc9.png)

**Comment by alexkcollier** [comment]
You may have better luck creating a new issue. What you're reporting
doesn't seem related.
