### ISSUE TITLE
Cannot read property 'renderRoute' of undefined

### ISSUE THREAD

**Issue by jjhesk** [nuxt/nuxt.js#6513]
I have the same issue as well. Just install 2.10.0 and the problem started acting. Node v10.15.3, and all projects with different nuxt version will have this error message.

Cannot read property 'renderRoute' of undefined                                                            18:06:13

  at Generator.afterGenerate (node_modules/@nuxt/generator/dist/generator.js:168:43)
@visualfanatic
@ConsoleTVs

**Comment by jjhesk** [comment]
same error in here

Generator.afterGenerate (node_modules/@nuxt/generator/dist/generator.js:168:43)

**Comment by dkade** [comment]
Same here...

TypeError: Cannot read property 'renderRoute' of undefined
    at Generator.generateRoute (.../node_modules/@nuxt/generator/dist/generator.js:222:42)

**Comment by kissge** [comment]
Same here.
Looks like a degression caused by https://github.com/nuxt/nuxt.js/commit/95e043f1679f9d3bf1f6508282ac0c6ec468f4d8 .
This change blocked `server` from being initialized (cf. https://github.com/nuxt/nuxt.js/blob/9ad02c4/packages/core/src/nuxt.js#L38-L40).
This looks like an emergent bug as it basically means `nuxt build` and `nuxt generate` are not working at all atm, and there's no workaround known (any ideas? cc: @clarkdo @pi0 )
Thanks :)

**Comment by vinayakkulkarni** [comment]
yep facing the same issue, trying with `yarn`, ref: https://github.com/nuxt/nuxt.js/issues/6514#issuecomment-538553205

**Comment by dkade** [comment]
Yes same with yarn, removed * nodes-modules and package-lock.json, did a clean yarn install, and when running yarn run build, I get exactly the same error.

**Comment by thebspin** [comment]
Same here, only on the build server i can actually build locally.

**Comment by tarakeshp** [comment]
I am facing similar in SPA mode
https://github.com/nuxt/nuxt.js/issues/6526

**Comment by saknarak** [comment]
I'm facing same problem for SPA mode
https://github.com/nuxt/nuxt.js/commit/95e043f1679f9d3bf1f6508282ac0c6ec468f4d8

Work around, edit file ```node_modules/@nuxt/cli/dist/cli-build.js```
line 81: change from
```
    const config = await cmd.getNuxtConfig({ dev: false, server: false, _build: true });
```
to
```
    const config = await cmd.getNuxtConfig({ dev: false, _build: true });
```

now I can ```nuxt build```

**Comment by vinayakkulkarni** [comment]
Should be fixed in [v2.10.1](https://github.com/nuxt/nuxt.js/pull/6529) since #6525 is now merged.. waiting to run `npm up` my project(s). ;)

**Comment by frederic117** [comment]
still got the error with v2.10.1

**Comment by thebspin** [comment]
> still got the error with v2.10.1

Works for me, you sure you also actually installed the new version?

**Comment by vinayakkulkarni** [comment]
> still got the error with v2.10.1

@frederic117 :

npm up && rm -rf node_modules/ package-lock.json && npm i

have you tried this?

**Comment by dkade** [comment]
Yes it is fixed! 

For yarn check if you have nuxt version pined in package.json, then:

`rm -Rf node_modules/ && rm yarn.lock && yarn`

**Comment by xaviervitali** [comment]
Hi,

i've the same issue i tried 

rm -R node_modules/ 
rm yarn.lock 
yarn

**Comment by frederic117** [comment]
I tried 
rm -Rf node_modules/ && rm yarn.lock && yarn
But still the same error 😭

**Comment by frederic117** [comment]
FATAL  Cannot read property 'renderRoute' of undefined
remote:
remote:   at ModuleContainer.cacheRenderer (node_modules/nuxt-ssr-cache/lib/middleware.js:64:30)
remote:   at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:190:34)
remote:   at promise.then (node_modules/@nuxt/utils/dist/utils.js:1802:43)
remote:   at process.runNextTicks [as _tickCallback] (internal/process/task_queues.js:52:5)
remote:   at Function.Module.runMain (internal/modules/cjs/loader.js:880:11)
remote:   at internal/main/run_main_module.js:21:11

**Comment by dkade** [comment]
You are still in the old version.

Check package.json: "nuxt": "^2.10.1"
