### ISSUE TITLE
Error when failed to load chunk on new deployment build (404 network issue)

### ISSUE THREAD

**Issue by cain** [nuxt/nuxt.js#6982]
### Version

[v2.11.0](https://github.com/nuxt.js/releases/tag/v2.11.0)

### Reproduction link

Sorry dont have Reproduction link :( 

### Steps to reproduce

1. Be active on NuxtJS site
2. Turn off prefetching nuxt-links in config.
3. Deploy new build, server removes all previous build files from the server and deploys new build files.
3. User still active on site clicks nuxt-link, resulting in ChunkLoadError with no error or redirect.

Example error:
```
Loading chunk 36 failed. (error: https://url/_nuxt/2789254cf3f01c089e12.js)
```

### What is expected ?

User to be reloaded: https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/client.js#L187

Also see: #3389

### What is actually happening?

Throwing error, but not being redirected to an error page.

### Additional comments?

Sorry for not having a Reproduction link, if anyone else is having this issue or has a workaround please let us know :) 

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10300">#c10300</a>)</em></sub></div>

**Comment by cain** [comment]
bump stale bot

**Comment by lxc455735702** [comment]
Do you have a solution? I also encountered the same problem @cain

**Comment by cain** [comment]
@lxc455735702 We enabled prefetching for the meanwhile

**Comment by jsbroks** [comment]
Same issue here!

**Comment by shrpne** [comment]
not stale

**Comment by Atinux** [comment]
We will look at it sorry about this

**Comment by Atinux** [comment]
I just tested locally and I do have the page reload happening when I have a failed chunk:

![Screenshot 2020-05-13 at 17 22 43](https://user-images.githubusercontent.com/904724/81832119-6d26ed00-953e-11ea-9482-bb73a741f5bb.png)

I disabled `router.prefetchLinks` as well.

**Comment by Atinux** [comment]
Could you please share the error that is displayed on the console? Maybe it does not goes inside [this condition](https://github.com/nuxt/nuxt.js/blob/dev/packages/vue-app/template/client.js#L188):

```js
if (/^Loading( CSS)? chunk (\d)+ failed\./.test(message)) {
    window.location.reload(true /* skip cache */)
    return // prevent error page blinking for user
}
```

**Comment by nicolashmln** [comment]
That's was that error on nuxt 2.11

<img width="1190" alt="Capture d’écran 2020-05-15 à 12 45 35" src="https://user-images.githubusercontent.com/22435892/82006007-2d7d1400-96aa-11ea-9d07-7475ed1dc6d4.png">

But it seems to be fixed on nuxt 2.12.2, the page reloads indeed

**Comment by cain** [comment]
fixed on 2.12.2, thanks @Atinux

**Comment by manniL** [comment]
Closing here then

**Comment by jsbroks** [comment]
@manniL I'm still getting this issue
![image](https://user-images.githubusercontent.com/24920936/82851175-f63e0c80-9ecc-11ea-9b0e-2b675941a8b7.png)
I'm on ``nuxt-edge 2.13.0-26500336.1e53e38f``

**Comment by Abdulla1995** [comment]
> 
> 
> fixed on 2.12.2, thanks @Atinux

I guess this only fixes CSS loading errors. But js loading error still existing on my production deployment. When I deploy new build with minor changes, I get Loading chunk failed error. I have upgraded 2.12.2 but there is no fix for this situation. Both SPA and Universal versions failed for me. 
@Atinux in your comment I see you added CSS error reloader to prevent such problems. But no js error loader fix existing. And still I cant found any solution how to show user that there is new deployment and need to reload page (the worst case - reload app without showing anything, but I can be sure that it will work after reload). Please answer this immediately, because NUXT applications all will fail such situation and this makes me feel I do code for nothing:/ .

**Comment by jsbroks** [comment]
I am also getting chunk loading errors in development. Once I get one I have to clear my cache and then it works. Very irritating

**Comment by janswist** [comment]
I have 2.13.2 and have the very same issue + related to https://github.com/nuxt/nuxt.js/issues/6338

Initial load is ok, then I click refresh and it loads indefinitely. I click refresh again and it loads, again refresh, again it goes on on and on. To get error message I had to interrupt refresh:
![image](https://user-images.githubusercontent.com/5583954/86041638-36e9f200-ba46-11ea-89a1-401ff36ae57e.png)

On incognito works flawlessly. Seems like @jsbroks is right - it has something to do with cache.

**Comment by bart** [comment]
Same issue here but only in dev mode. In my opinion it has something todo with code splitting of JS files. Any idea?

**Comment by cain** [comment]
@bart Interesting, do you know why this fixes the issue?

**Comment by bart** [comment]
I think it has something to do with paths browsers try to cache when SSR loading a page in advance. Also found this: https://blog.francium.tech/vue-lazy-routes-loading-chunk-failed-9ee407bbd58

**Comment by chuoke** [comment]
the same issue, after upgrading. According to your comments, my site works again, by configuring filenames.
And I found the doc is wrong:
in the [doc](https://nuxtjs.org/api/configuration-build#filenames), say filenames default is like this:
```
{
  app: ({ isDev }) => isDev ? '[name].js' : '[contenthash].js',
  chunk: ({ isDev }) => isDev ? '[name].js' : '[contenthash].js',
  css: ({ isDev }) => isDev ? '[name].css' : '[contenthash].css',
  img: ({ isDev }) => isDev ? '[path][name].[ext]' : 'img/[contenthash:7].[ext]',
  font: ({ isDev }) => isDev ? '[path][name].[ext]' : 'fonts/[contenthash:7].[ext]',
  video: ({ isDev }) => isDev ? '[path][name].[ext]' : 'videos/[contenthash:7].[ext]'
}
```

but in the [source code](https://github.com/nuxt/nuxt.js/blob/1a70824a223dde97cf9f60c9b65c935286b05abb/packages/config/src/config/build.js#L15) is like this
```
{
    // { isDev, isClient, isServer }
    app: ({ isDev, isModern }) => isDev ? `${isModern ? 'modern-' : ''}[name].js` : '[name].[contenthash:7].js',
    chunk: ({ isDev, isModern }) => isDev ? `${isModern ? 'modern-' : ''}[name].js` : '[name].[contenthash:7].js',
    css: ({ isDev }) => isDev ? '[name].css' : '[name].[contenthash:7].css',
    img: ({ isDev }) => isDev ? '[path][name].[ext]' : 'img/[name].[contenthash:7].[ext]',
    font: ({ isDev }) => isDev ? '[path][name].[ext]' : 'fonts/[name].[contenthash:7].[ext]',
    video: ({ isDev }) => isDev ? '[path][name].[ext]' : 'videos/[name].[contenthash:7].[ext]'
  }
```

**Comment by manniL** [comment]
> 
> 
> the same issue, after upgrading. According to your comments, my site works again, by configuring filenames.
> And I found the doc is wrong:
> in the [doc](https://nuxtjs.org/api/configuration-build#filenames), say filenames default is like this:
> 
> ```
> {
>   app: ({ isDev }) => isDev ? '[name].js' : '[contenthash].js',
>   chunk: ({ isDev }) => isDev ? '[name].js' : '[contenthash].js',
>   css: ({ isDev }) => isDev ? '[name].css' : '[contenthash].css',
>   img: ({ isDev }) => isDev ? '[path][name].[ext]' : 'img/[contenthash:7].[ext]',
>   font: ({ isDev }) => isDev ? '[path][name].[ext]' : 'fonts/[contenthash:7].[ext]',
>   video: ({ isDev }) => isDev ? '[path][name].[ext]' : 'videos/[contenthash:7].[ext]'
> }
> ```
> 
> but in the [source code](https://github.com/nuxt/nuxt.js/blob/1a70824a223dde97cf9f60c9b65c935286b05abb/packages/config/src/config/build.js#L15) is like this
> 
> ```
> {
>     // { isDev, isClient, isServer }
>     app: ({ isDev, isModern }) => isDev ? `[name]${isModern ? '.modern' : ''}.js` : `[name].[contenthash:7]${isModern ? '.modern' : ''}.js`,
>     chunk: ({ isDev, isModern }) => isDev ? `[name]${isModern ? '.modern' : ''}.js` : `[name].[contenthash:7]${isModern ? '.modern' : ''}.js`,
>     css: ({ isDev }) => isDev ? '[name].css' : '[name].[contenthash:7].css',
>     img: ({ isDev }) => isDev ? '[path][name].[ext]' : 'img/[name].[contenthash:7].[ext]',
>     font: ({ isDev }) => isDev ? '[path][name].[ext]' : 'fonts/[name].[contenthash:7].[ext]',
>     video: ({ isDev }) => isDev ? '[path][name].[ext]' : 'videos/[name].[contenthash:7].[ext]'
>   }
> ```

PR welcome!
