### ISSUE TITLE
Full-static generated site attempt to fetch payloads for non-generated page

### ISSUE THREAD

**Issue by FreekVR** [nuxt/nuxt.js#7559]
### Version

[v2.13.0](https://github.com/nuxt.js/releases/tag/v2.13.0)

### Reproduction link

[https://codesandbox.io/s/silly-tesla-blj2f?file=/pages/_slug.vue](https://codesandbox.io/s/silly-tesla-blj2f?file=/pages/_slug.vue)

### Steps to reproduce

- Create a dynamic route eg. `pages/_slug.vue`
- Make sure this page is not generated and /or crawlable
- Navigate to the page: https://blj2f.sse.codesandbox.io/foo
- A 404 console error is logged

### What is expected ?

Nuxt doesn't attempt to fetch payloads that don't exist

### What is actually happening?

404 errors are logged to the browser console

<div align="right"><sub><em>This bug report is available on <a href="https://cmty.app/nuxt">Nuxt</a> community (<a href="https://cmty.app/nuxt/nuxt.js/issues/c10802">#c10802</a>)</em></sub></div>

**Comment by ziosa** [comment]
Hello @FreekVR ,

Are you sure that there is a bug?
For me seems to work properly:

<img width="1856" alt="image" src="https://user-images.githubusercontent.com/629677/85411413-9e94ce80-b568-11ea-8391-fb0991ca7263.png">

**Comment by FreekVR** [comment]
@ziosa it doesn't show up in the console / terminal on codesandbox itself, but if you click the little button on the top-right to open it in a dedicated window, you should see a 404 for payload.js in your devtools / browser console.

**Comment by pi0** [comment]
Hi @FreekVR.This issue is fixed with v2.13.3 (#7657) 

Forked sandbox:
- https://codesandbox.io/s/red-framework-2gwo7?file=/nuxt.config.js
- https://2gwo7.sse.codesandbox.io/aa

**Comment by divine** [comment]
Hi @pi0, it's not fixed, you can see 404 payload error when used with nuxt-i18n.

See this sandbox:

- https://codesandbox.io/s/heuristic-cherry-onrvu?file=/nuxt.config.js
- https://onrvu.sse.codesandbox.io/about/


Thanks!

**Comment by divine** [comment]
@pi0 @Atinux could you please reopen this issue or should I create a new issue? It's not fixed completely.

Thanks!

**Comment by Atinux** [comment]
@divine indeed please create a reproduction, with a GitHub repo since it's hard to actually debug full static on CodeSandbox since it's dev mode only.

You can also use https://surge.sh to easily deploy once statically generated (it's free).
