### ISSUE TITLE
Generate Crawler trying to build external links that start with //

### ISSUE THREAD

**Issue by mystrdat** [nuxt/nuxt.js#7805]
### Versions

- nuxt: 2.14.0

### Steps to reproduce

With the following code in a component:

```
<a
  href="//url.com/something/somethingElse/"
  target="_blank"
  rel="noopener"
>
```

The new generate crawler will attempt to build the links and fail with `Error generating route "//url.com/something/somethingElse/": This page could not be found` during `nuxt generate`.

### What is Expected?

Crawler should disregard links that are clearly external (begin with `//`).

### What is actually happening?

Crawler tries to generate pages for these links.

**Comment by pi0** [comment]
Should be fixed with [v2.14.1](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.1)

**Comment by LeoSeyers** [comment]
I've updated to 2.14.1 and I still have a similar issue with my JSON api. Probably the way it's escaped?
I've turned it the crawler off temporarily.

```
{
"rendered": "\n<p> ...<strong>We’ve just created Bidules <a href=\"https://www.shop.bidules.be/bidules-online-shop/gift-card\"> ..."
}
```


And the error :

```
ERROR /https://www.shop.bidules.be/bidules-online-shop/gift-card                                                                                                                       10:21:06  

Error: C:\Users\butterchikita-2020\Desktop\Frontend\nuxt\bidules-nuxt\dist\_nuxt\static\1596615661\https:\www.shop.bidules.be\bidules-online-shop\gift-card contains invalid WIN32 path characters. 
    at Object.mkdirs (C:\Users\butterchikita-2020\Desktop\Frontend\nuxt\bidules-nuxt\node_modules\fs-extra\lib\mkdirs\mkdirs.js:18:22)
    at C:\Users\butterchikita-2020\Desktop\Frontend\nuxt\bidules-nuxt\node_modules\universalify\index.js:13:12
    at new Promise (<anonymous>)
    at Object.mkdirs (C:\Users\butterchikita-2020\Desktop\Frontend\nuxt\bidules-nuxt\node_modules\universalify\index.js:7:14)
    at Generator.generateRoute (C:\Users\butterchikita-2020\Desktop\Frontend\nuxt\bidules-nuxt\node_modules\@nuxt\generator\dist\generator.js:391:25)
    at async C:\Users\butterchikita-2020\Desktop\Frontend\nuxt\bidules-nuxt\node_modules\@nuxt\generator\dist\generator.js:234:13
    at async Promise.all (index 1)
    at async Generator.generateRoutes (C:\Users\butterchikita-2020\Desktop\Frontend\nuxt\bidules-nuxt\node_modules\@nuxt\generator\dist\generator.js:229:7)
    at async Generator.generate (C:\Users\butterchikita-2020\Desktop\Frontend\nuxt\bidules-nuxt\node_modules\@nuxt\generator\dist\generator.js:121:20)
    at async generate (C:\Users\butterchikita-2020\Desktop\Frontend\nuxt\bidules-nuxt\node_modules\@nuxt\cli\dist\cli-generate.js:114:3)
    at async Object.run (C:\Users\butterchikita-2020\Desktop\Frontend\nuxt\bidules-nuxt\node_modules\@nuxt\cli\dist\cli-generate.js:329:7)
    at async NuxtCommand.run (C:\Users\butterchikita-2020\Desktop\Frontend\nuxt\bidules-nuxt\node_modules\@nuxt\cli\dist\cli-index.js:2798:7)
```
