### ISSUE TITLE
Weird behavior with trailingSlash=false and child routes

### ISSUE THREAD

**Issue by rchl** [nuxt/nuxt.js#7823]
### Versions

- nuxt: v2.14.0
- node: v12.18.2

### Reproduction

https://codesandbox.io/s/nuxt-trailingslash-false-and-child-routes-3etm9?file=/pages/posts.vue

<details>
<summary>Nuxt configuration</summary>

```
  router: {
    trailingSlash: false
  },
```

</details>

<details>
<summary>Routes configuration</summary>

```
  routes: [{
    path: "/posts",
    component: _ad4aa402,
    pathToRegexpOptions: {"strict":true},
    children: [{
      path: "",
      component: _19067942,
      pathToRegexpOptions: {"strict":true},
      name: "posts"
    }, {
      path: ":slug?",
      component: _174fd7fa,
      pathToRegexpOptions: {"strict":true},
      name: "posts-slug"
    }]
  }, {
    path: "/",
    component: _00cac37e,
    pathToRegexpOptions: {"strict":true},
    name: "index"
  }],

  fallback: false
}
```

</details>

Directory structure:
![Screenshot 2020-07-31 at 13 40 45](https://user-images.githubusercontent.com/153197/89031783-76507a80-d333-11ea-93ba-4ede0340b5b9.png)

### Steps to reproduce

With a directory structure like pictured above (where the `posts.vue` parent route contains `<router-view>`), navigate to both `/posts` and `/posts/`.

### What is Expected?

I'm not sure but possibly the opposite of what is happening right now.

### What is actually happening?

 - Navigating to `/posts` loads the `posts/_slug` child route.
 - Navigating to `/posts/` loads the `posts/index` child route.

**Comment by rchl** [comment]
Results for the previous version of Nuxt (2.13.3):

Navigating to /posts does not load any child route
Navigating to /posts/ loads the posts/index child route.

<details>
<summary>Routes configuration</summary>

```
  routes: [{
    path: "/posts",
    component: _ad4aa402,
    pathToRegexpOptions: {"strict":true},
    name: "posts",
    children: [{
      path: "",
      component: _19067942,
      pathToRegexpOptions: {"strict":true},
      name: "posts"
    }, {
      path: ":slug",
      component: _174fd7fa,
      pathToRegexpOptions: {"strict":true},
      name: "posts-slug"
    }]
  }, {
    path: "/",
    component: _00cac37e,
    pathToRegexpOptions: {"strict":true},
    name: "index"
  }],

  fallback: false
}
```

</details>

Notice that in the new version of Nuxt the `_slug` route has `:slug?` path while in the older version it has `:slug`. This is probably related to parent route no longer having a `name` (which is likely the right thing to do).

**Comment by rchl** [comment]
@manniL What do you think is expected here regarding the child `_slug` route being optional? Since there is an `index` route besides it, I would think that it shouldn't be optional.

This also seems related to #7843 so CC'ing @farnabaz

**Comment by manniL** [comment]
So, with `trailingSlash` being `false`, I'd expect to have `/posts` to show the index page while `/posts/` shouldn't show any and return a 404. `/posts/foo` should then show the `_slug.vue` content while `/posts/foo/` should return a 404.

**Comment by rchl** [comment]
@farnabaz since you've done some related changes, do you want to tackle this too? :)

Or do you have an opinion at least and does it match with @manniL 's?

**Comment by farnabaz** [comment]
@manniL Take a look at https://github.com/nuxt/nuxt.js/pull/6594/files#diff-1288a325a940f45fdc5707e5485c442aR75

When we replace `defaultChildRoute.name` with parent's name, we remove `-index` from `defaultChildRoute.name`.  
By removing `-index` from `defaultChildRoute.name`, `:slug` in the other child will become optional and it causes the issue.

**Comment by rchl** [comment]
I'm not updating Nuxt dependency in `nuxt-i18n` until this is fixed. :P

**Comment by rchl** [comment]
..

**Comment by aviramaz** [comment]
Bump, any updates/progress?

**Comment by pi0** [comment]
This should be fixed in [v2.14.8](https://github.com/nuxt/nuxt.js/releases/tag/v2.14.8). Please reopen if not.

**Comment by rchl** [comment]
There is still an issue with `trailingSlash: true` but I'll create a separate issue for that.

**Comment by rchl** [comment]
New issue: #8422
