### ISSUE TITLE
[2.15.5] Rule can only have one resource source

### ISSUE THREAD

**Issue by rob-tech** [nuxt/nuxt.js#9268]
I have upgraded nuxt to v.2.15.5. I'm using Node v14 :

```
 ERROR  Rule can only have one resource source (provided resource and test + include + exclude) in {                        11:48:55  
  "use": [
    {
      "loader": "C:\\Users\\xxx\\xxx\\node_modules\\babel-loader\\lib\\index.js",
      "options": {
        "configFile": false,
        "babelrc": false,
        "cacheDirectory": true,
        "envName": "client",
        "presets": [
          [
            "C:\\Users\\xxx\\xxx\\node_modules\\@nuxt\\babel-preset-app\\src\\index.js",
            {
              "corejs": {
                "version": 3
              }
            }
          ]
        ]
      },
      "ident": "clonedRuleSet-4[0].rules[0].use[0]"
    }
  ]
}

  "use": [
  {
  "loader": "C:\\Users\\xxx\\xxx\\node_modules\\babel-loader\\lib\\index.js",
  "options": {
  "configFile": false,
  "babelrc": false,
  "cacheDirectory": true,
  "envName": "client",
  "presets": [
  [
  "C:\\Users\\xxx\\xxx\\node_modules\\@nuxt\\babel-preset-app\\src\\index.js",
  {
  "corejs": {
  "version": 3
  }
  }
  ]
  ]
  },
  "ident": "clonedRuleSet-4[0].rules[0].use[0]"
  }
  ]
  }
  at checkResourceSource (node_modules\@nuxt\webpack\node_modules\webpack\lib\RuleSet.js:167:11)
  at Function.normalizeRule (node_modules\@nuxt\webpack\node_modules\webpack\lib\RuleSet.js:198:4)
  at node_modules\@nuxt\webpack\node_modules\webpack\lib\RuleSet.js:110:20
  at Array.map (<anonymous>)
  at Function.normalizeRules (node_modules\@nuxt\webpack\node_modules\webpack\lib\RuleSet.js:109:17)
  at new RuleSet (node_modules\@nuxt\webpack\node_modules\webpack\lib\RuleSet.js:104:24)
  at new NormalModuleFactory (node_modules\@nuxt\webpack\node_modules\webpack\lib\NormalModuleFactory.js:115:18)
  at Compiler.createNormalModuleFactory (node_modules\@nuxt\webpack\node_modules\webpack\lib\Compiler.js:636:31)
  at Compiler.newCompilationParams (node_modules\@nuxt\webpack\node_modules\webpack\lib\Compiler.js:653:30)
  at Compiler.compile (node_modules\@nuxt\webpack\node_modules\webpack\lib\Compiler.js:661:23)
  at node_modules\@nuxt\webpack\node_modules\webpack\lib\Watching.js:77:18
  at AsyncSeriesHook.eval [as callAsync] (eval at create (node_modules\@nuxt\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:42:1)
  at AsyncSeriesHook.lazyCompileHook (node_modules\@nuxt\webpack\node_modules\tapable\lib\Hook.js:154:20)
  at Watching._go (node_modules\@nuxt\webpack\node_modules\webpack\lib\Watching.js:41:32)
  at node_modules\@nuxt\webpack\node_modules\webpack\lib\Watching.js:33:9
  at Compiler.readRecords (node_modules\@nuxt\webpack\node_modules\webpack\lib\Compiler.js:529:11)
```

**Comment by baijii** [comment]
I had a similar problem. It seemed as it now needs a peer dependency of webpack@4 to work. For me after doing

```bash
npm install --save-dev webpack@4
```

it worked again. But it seems as we're now using Webpack 5 and 4. Not ideal.

**Comment by laportem** [comment]
When will the fix be released and how do we apply the fix

**Comment by pi0** [comment]
Quick fix for npm users until next release: change `@types/nuxt` to `@types/nuxt-edge` in package.json and recreate lock file.

**Comment by julien1619** [comment]
The workaround didn't work for us. We added this dev-dependency to make it work:
```
"@types/webpack-dev-middleware": "4.1.2",
```

**Comment by husayt** [comment]
> Quick fix for npm users until next release: change `@types/nuxt` to `@types/nuxt-edge` in `package.json` and recreate lock file.

You probably mean `@nuxt/types-edge`

**Comment by husayt** [comment]
I had to add webpack dependency directly for it to work
"webpack": "^4.46.0"

**Comment by rob-tech** [comment]
Whenever I apply the workarounds since the loose babel console error I keep getting Error: Failed to load config "developit" to extend from. But then without the workounds its the error mentioned in this bug report that I get. Very odd.

**Comment by laportem** [comment]
try these workaround and the only ne that seems to work the suggestion from @julien1619 
add  "@types/webpack-dev-middleware": "4.1.2", to dev-dependency

**Comment by pi0** [comment]
Should be fixed in 2.15.6 (please ensure to cleanup `package.lock.json`  / `yarn.lock`)

**Comment by rob-tech** [comment]
> Should be fixed in 2.15.6 (please ensure to cleanup `package.lock.json` / `yarn.lock` and update both `nuxt` and `@nuxt/types`)
> 
> If encountered same error, please report here otherwise please open a new issue.

Solved!

**Comment by sebj54** [comment]
I had still the same problem with 2.15.8. I had two warnings when I ran `npm run dev`: 

```
 WARN  webpack@5.52.1 is installed but ^4.46.0 is expected

 WARN  sass-loader@12.1.0 is installed but ^10.1.1 is expected
```

I just pinned/added the dependencies in the expected version, ran `npm install` and it worked after that.

I think the cause of the problem is an incompatibility between new `package-lock.json` format and nuxt.
